'use strict';

// Mots anglais courants de 8 lettres, utilisés pour générer un code maître
// facile à mémoriser et à retranscrire (au lieu d'une chaîne aléatoire).
const RAW_WORDS = [
  'ACCIDENT', 'ACTIVATE', 'AIRCRAFT', 'AIRPLANE', 'ALPHABET', 'AMERICAN', 'ANALYSIS',
  'ANYTHING', 'APPETITE', 'ARGUMENT', 'ATTITUDE', 'AUDIENCE', 'BACKYARD', 'BALANCED',
  'BASEBALL', 'BATHROOM', 'BIRTHDAY', 'BLESSING', 'BOUNDARY', 'BUILDING', 'BUSINESS',
  'CALENDAR', 'CAMPAIGN', 'CAPACITY', 'CATALOGS', 'CHAIRMAN', 'CHAMBERS', 'CHANGING',
  'CHANNELS', 'CHARMING', 'CHEMICAL', 'CHILDREN', 'CIRCUITS', 'CLASSICS', 'COLLAPSE',
  'COMBINED', 'COMEDIAN', 'COMMENTS', 'COMPLETE', 'COMPOUND', 'COMPUTER', 'CONCERNS',
  'CONCRETE', 'CONFIRMS', 'CONTACTS', 'CONTINUE', 'CONTRACT', 'CONTRARY', 'CONTROLS',
  'COOKBOOK', 'COUNTIES', 'COUNTING', 'COVERAGE', 'CREATION', 'CREATIVE', 'CRITERIA',
  'CULTURAL', 'CUSTOMER', 'DAUGHTER', 'DEADLINE', 'DECREASE', 'DEDICATE', 'DELIVERY',
  'DESIGNER', 'DETAILED', 'DIALOGUE', 'DIAMONDS', 'DIRECTOR', 'DISASTER', 'DISCOUNT',
  'DISTANCE', 'DIVISION', 'DOCTRINE', 'DOMESTIC', 'DOWNLOAD', 'DOWNTOWN', 'DRAWBACK',
  'DRIVEWAY', 'DURATION', 'EARRINGS', 'ECONOMIC', 'EDUCATED', 'ELECTION', 'ELECTRIC',
  'ELEPHANT', 'EMOTIONS', 'EMPHASIS', 'ENERGIES', 'ENGAGING', 'ENVELOPE', 'EPISODES',
  'EQUATION', 'ESCALATE', 'EVENINGS', 'EVIDENCE', 'EXCHANGE', 'EXERCISE', 'EXPECTED',
  'EXPLORER', 'FAIRNESS', 'FAREWELL', 'FASHIONS', 'FEEDBACK', 'FESTIVAL', 'FINISHED',
  'FOOTBALL', 'FOOTNOTE', 'FORECAST', 'FOREHEAD', 'FORTRESS', 'FORWARDS', 'FRACTION',
  'FREEDOMS', 'FRIENDLY', 'FUNCTION', 'GALLOPED', 'GARDENER', 'GATEWAYS', 'GENERATE',
  'GRADUATE', 'GRAPHICS', 'GUIDANCE', 'HANDBOOK', 'HAPPIEST', 'HARDWARE', 'HARMONIC',
  'HEADACHE', 'HEADLINE', 'HEAVENLY', 'HIGHWAYS', 'HISTORIC', 'HOLIDAYS', 'HOMELAND',
  'HOSPITAL', 'IMPORTED', 'INCLUDED', 'INCREASE', 'INDIRECT', 'INDUSTRY', 'INFECTED',
  'INTEREST', 'INTERNAL', 'INTERVAL', 'INVASION', 'JOURNALS', 'JOURNEYS', 'JUDGMENT',
  'JUNCTION', 'KEYBOARD', 'KINGDOMS', 'KITCHENS', 'LANGUAGE', 'LAUGHTER', 'LEARNING',
  'LIGHTING', 'LITERARY', 'LOCATION', 'LOGISTIC', 'MACHINES', 'MAGAZINE', 'MAINLAND',
  'MAJORITY', 'MANAGING', 'MARRIAGE', 'MEANINGS', 'MEASURES', 'MECHANIC', 'MEDICINE',
  'MEETINGS', 'MERCHANT', 'MIDNIGHT', 'MILITARY', 'MINERALS', 'MOMENTUM', 'MONITORS',
  'MONSTERS', 'MOUNTAIN', 'MOVEMENT', 'MUSICIAN', 'MYSTICAL', 'NATIONAL', 'NEIGHBOR',
  'NETWORKS', 'NOTEBOOK', 'NOTICING', 'NUMEROUS', 'OBSTACLE', 'OFFICIAL', 'OPERATOR',
  'ORDINARY', 'ORGANISM', 'OUTBREAK', 'OUTCOMES', 'OUTDOORS', 'OVERCOME', 'OVERSEAS',
  'PACKAGES', 'PAINTING', 'PANORAMA', 'PARALLEL', 'PARTICLE', 'PASSPORT', 'PATTERNS',
  'PERFUMES', 'PHYSICAL', 'PICTURES', 'PLANNING', 'PLATFORM', 'POPULATE', 'POSITION',
  'POSTCARD', 'POWERFUL', 'PRACTICE', 'PRECIOUS', 'PREDATOR', 'PRESENCE', 'PRINCESS',
  'PROBLEMS', 'PRODUCED', 'PROGRAMS', 'PROVINCE', 'PURCHASE', 'QUESTION', 'RACCOONS',
  'RAINBOWS', 'READABLE', 'RECEIVED', 'RECOVERY', 'REGIONAL', 'RELATIVE', 'RELEASED',
  'REMEMBER', 'RESEARCH', 'RESIDENT', 'RESOURCE', 'RESPONSE', 'REVENUES', 'ROADSIDE',
  'ROMANTIC', 'ROOMMATE', 'SANDWICH', 'SATURDAY', 'SCHEDULE', 'SCIENCES', 'SEASONAL',
  'SECONDLY', 'SELECTED', 'SENTENCE', 'SEQUENCE', 'SHOULDER', 'SIMPLIFY', 'SLIPPERY',
  'SMARTEST', 'SNOWFALL', 'SOFTWARE', 'SOLITARY', 'SOMEBODY', 'SPACIOUS', 'SPECIMEN',
  'SPELLING', 'SPLENDID', 'STANDARD', 'STATUTES', 'STORMING', 'STRAIGHT', 'STRANGER',
  'STRATEGY', 'STRENGTH', 'STRUGGLE', 'STUDENTS', 'SUITCASE', 'SUNSHINE', 'SUPPLIES',
  'SUPPORTS', 'SURGICAL', 'SURVIVAL', 'SYMPHONY', 'TEACHERS', 'TERRIBLE', 'THINKING',
  'THOUSAND', 'TOGETHER', 'TOMORROW', 'TRAINING', 'TREASURE', 'TRIANGLE', 'TROPICAL',
  'TUESDAYS', 'TWILIGHT', 'UMBRELLA', 'UNIVERSE', 'UPGRADED', 'VACATION', 'VALIDATE',
  'VETERANS', 'VILLAGES', 'VIOLENCE', 'VOLCANIC', 'WARRANTY', 'WATCHDOG', 'WEEKENDS',
  'WHATEVER', 'WILDLIFE', 'WIRELESS', 'WORKSHOP', 'YOURSELF',
];

// Filet de sécurité : ne garde que des mots de 8 lettres en majuscules.
const WORDS_8 = RAW_WORDS.filter(w => w.length === 8).map(w => w.toUpperCase());

module.exports = { WORDS_8 };
